export const exerciseIconMap: Record<string, { icon: string; color: string }> = {
  'Caminata': { icon: 'directions-walk', color: '#10b981' },
  'Trote Básico': { icon: 'directions-run', color: '#047857' },
  'Pausas Activas': { icon: 'self-improvement', color: '#fbbf24' },
  'Fútbol': { icon: 'sports-soccer', color: '#22c55e' },
  'Ciclismo': { icon: 'directions-bike', color: '#3b82f6' },
  'Natación': { icon: 'pool', color: '#06b6d4' },
  'Yoga': { icon: 'self-improvement', color: '#8b5cf6' },
  'Entrenamiento de Fuerza': { icon: 'fitness-center', color: '#ef4444' },
  'HIIT': { icon: 'flash-on', color: '#f59e0b' },
  'Pilates': { icon: 'accessibility-new', color: '#db2777' },
  'Aeróbicos': { icon: 'airline-seat-recline-normal', color: '#8b5cf6' },
  'Danza': { icon: 'music-note', color: '#ec4899' },
  'Zumba': { icon: 'music-note', color: '#f97316' },
  'Saltar la cuerda': { icon: 'replay', color: '#f43f5e' },
  'Remo': { icon: 'rowing', color: '#0284c7' },
  'Elíptica': { icon: 'fitness-center', color: '#2563eb' },
  'Senderismo': { icon: 'terrain', color: '#4ade80' },
  'Escalada': { icon: 'terrain', color: '#22c55e' },
  'Boxeo': { icon: 'sports-mma', color: '#dc2626' },
  'Artes Marciales': { icon: 'sports-kabaddi', color: '#7c3aed' },
  'Tai Chi': { icon: 'self-improvement', color: '#4ade80' },
  'Estiramiento': { icon: 'accessibility-new', color: '#a3e635' },
  'CrossFit': { icon: 'fitness-center', color: '#f97316' },
  'Spinning': { icon: 'directions-bike', color: '#6366f1' },
  'Kickboxing': { icon: 'sports-kabaddi', color: '#ef4444' },
  'Barre': { icon: 'accessibility', color: '#ec4899' },
  'Peso Corporal': { icon: 'fitness-center', color: '#f87171' },
  'Kettlebell': { icon: 'fitness-center', color: '#fbbf24' },
  'TRX': { icon: 'fitness-center', color: '#8b5cf6' },
  'Bandas de Resistencia': { icon: 'fitness-center', color: '#10b981' },
  'Subir Escaleras': { icon: 'stairs', color: '#6b7280' },
  'Esquí': { icon: 'downhill-skiing', color: '#0284c7' },
  'Snowboard': { icon: 'snowboarding', color: '#0ea5e9' },
  'Surf': { icon: 'surfing', color: '#3b82f6' },
  'Patinaje': { icon: 'roller-skate', color: '#f472b6' },
  'Equitación': { icon: 'emoji-nature', color: '#4ade80' },
  'Canotaje': { icon: 'kayaking', color: '#06b6d4' },
  'Kayak': { icon: 'kayaking', color: '#0ea5e9' },
  'Patinaje en línea': { icon: 'roller-skate', color: '#f43f5e' },
  'Parkour': { icon: 'directions-run', color: '#f59e0b' },
  'Entrenamiento en Circuito': { icon: 'fitness-center', color: '#6366f1' },
};
